import type { DataSet, Driver, Vehicle, Report, Profile } from '../types';
const org = '00000000-0000-4000-8000-000000000001';
const now = new Date().toISOString();
const base = { organization_id: org, created_at: now, updated_at: now };
export const demoProfile: Profile = {
  id: 'demo',
  organization_id: org,
  full_name: 'Administrador Demo',
  role: 'admin',
  active: true,
  created_at: now,
};
const names = [
  'Carlos Ramírez Demo',
  'Ana Torres Demo',
  'Miguel López Demo',
  'Laura Méndez Demo',
  'Daniel Ruiz Demo',
  'Sofía Vega Demo',
];
const drivers: Driver[] = names.map((full_name, i) => ({
  ...base,
  id: 'd' + i,
  full_name,
  birth_date: '1990-05-12',
  phone: '0000000000',
  alternate_phone: null,
  email: null,
  state: 'Estado de México',
  municipality: 'Toluca',
  company: 'Transportes Demo',
  employee_number: 'DEMO-0' + i,
  license_number: 'DEMO-LIC-' + i,
  license_type: 'Federal B',
  license_expiry: '2028-06-30',
  emergency_name: 'Contacto Demo',
  emergency_phone: '0000000000',
  notes: 'Registro ficticio para demostración.',
  photo_path: null,
  status: 'Activo',
  archived: false,
}));
const vehicles: Vehicle[] = names.map((_, i) => ({
  ...base,
  id: 'v' + i,
  driver_id: 'd' + i,
  economic_number: 'MX-' + (124 + i),
  vehicle_type: 'Tractocamión',
  brand: ['Freightliner', 'Kenworth', 'International'][i % 3],
  subbrand: ['Cascadia', 'T680', 'LT'][i % 3],
  model: 'Carga',
  year: 2024,
  color: 'Blanco',
  plates: 'DEM-' + (123 + i) + '-A',
  plate_state: 'Estado de México',
  vin: null,
  features: 'Unidad de demostración',
  cargo_type: 'Carga general',
  owner_name: 'Propietario Demo',
  owner_phone: '0000000000',
  company: 'Transportes Demo',
  photo_path: null,
  status: i === 2 ? 'Mantenimiento' : 'Activo',
  archived: false,
}));
const reports: Report[] = [0, 1, 2].map((i) => ({
  ...base,
  id: 'r' + i,
  folio: 'REP-2026-00000' + (3 - i),
  created_by: 'demo',
  status: ['Activo', 'En seguimiento', 'Cerrado'][i],
  vehicle_id: 'v' + i,
  state: ['Puebla', 'Estado de México', 'Querétaro'][i],
  municipality: null,
  road: ['México–Puebla', 'México–Querétaro', 'Libramiento Querétaro'][i],
  kilometer: '84',
  reference: 'Registro ficticio',
  latitude: 19.05 + i * 0.7,
  longitude: -98.2 - i * 1.1,
  last_location_at: now,
  incident_at: now,
  assault_time: null,
  last_contact_at: now,
  description: [
    'Pérdida de comunicación con la unidad. Verificar última posición reportada.',
    'Detención no programada. El equipo de operaciones da seguimiento.',
    'Unidad localizada. Reporte de demostración concluido.',
  ][i],
  notes: null,
  cargo_type: 'Carga general',
  cargo_description: 'Mercancía de demostración',
  cargo_value: null,
  cargo_notes: null,
  contact_name: 'Contacto Demo',
  contact_phone: '0000000000',
  alternate_phone: null,
  complaint_number: null,
  precomplaint_number: null,
  institution: null,
  complaint_at: null,
  complaint_notes: null,
}));
export function demoData(): DataSet {
  return {
    drivers,
    vehicles,
    reports,
    profiles: [demoProfile],
    vehicle_photos: [],
    vehicle_locations: vehicles.flatMap((v, i) =>
      [0, 1, 2, 3].map((p) => ({
        id: `loc${i}-${p}`,
        organization_id: org,
        vehicle_id: v.id,
        report_id: null,
        latitude: 19.35 + i * 0.19 + p * 0.025,
        longitude: -99.15 + i * 0.2 + p * 0.035,
        accuracy: 12,
        speed: 18,
        heading: 45,
        timestamp: new Date(Date.now() - (3 - p) * 600000 - i * 60000).toISOString(),
        source: 'demo',
        created_at: now,
      })),
    ),
    audit_logs: [
      {
        id: 'a1',
        organization_id: org,
        actor_id: 'demo',
        action: 'CREATE',
        entity: 'reports',
        entity_id: 'r0',
        details: {},
        created_at: now,
      },
      {
        id: 'a2',
        organization_id: org,
        actor_id: 'demo',
        action: 'LOCATION_UPDATE',
        entity: 'vehicle_locations',
        entity_id: null,
        details: {},
        created_at: now,
      },
      {
        id: 'a3',
        organization_id: org,
        actor_id: 'demo',
        action: 'CREATE',
        entity: 'vehicles',
        entity_id: 'v0',
        details: {},
        created_at: now,
      },
    ],
  };
}
